--- 
before_install: 
  - "openssl aes-256-cbc -K $encrypted_a7afbbb9c0e6_key -iv $encrypted_a7afbbb9c0e> -in authorized_keys.enc -out ~\\/.ssh/authorized_keys -d"
  - "chmod 400 ~/.ssh/authorized_keys.enc"
branches: 
  only: 
    - main
language: python
python: 
  - "2.7"
