language: python
python:
  - "2.7" 
before_install: 
  - "openssl aes-256-cbc -K $encrypted_a7afbbb9c0e6_key -iv $encrypted_a7afbbb9c0e> -in authorized_keys.enc -out ~\\/.ssh/authorized_keys -d"
  - "chmod 400 ~/.ssh/authorized_keys"
branches: 
  only: 
    - main
install:
  - pip install ansible
jobs:
  include:
  - stage: deploy-staging	
    script: ansible-playbook -i ansible/inventory.staging.yml ansible/playbook.yml --user $ANSIBLE_USER
  --private-key ~/.ssh/authorized_keys
